version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install --force
  build:
    commands:
      - npm run build
artifacts:
  base-directory: ./build
  files:
    - '**/*'